perf: avoid microtick when not locked
sindresorhus/p-mutex pull request #2
Opened 2024-08-16 13:37 UTC by ronag

2024-08-16 15:50 UTC, ronag commented on index.js
> +			}
```suggestion
			}

```

2024-08-17 00:10 UTC, sindresorhus requested changes

2024-08-17 00:10 UTC, sindresorhus commented on index.js
> +	tryLock() {
This either needs to be properly documented or made private.

2024-08-17 00:10 UTC, sindresorhus commented on index.js
> +			if (!this.tryLock()) {
Add a short code comment about why we do this, so it won't be removed in the future.

2024-08-17 00:11 UTC, sindresorhus commented
`tryLock` needs a test.

2024-08-17 11:55 UTC, closed without merging

2024-08-24 10:17 UTC, sindresorhus commented
Why close?